default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  database: app_development

test:
  <<: *default
  username: postgres
  database: app_test

production:
  <<: *default
  username: postgres
  database: app_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
